/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MaquinaExpendedora;

import java.util.Stack;
import java.util.LinkedList;
import java.util.Queue;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class ExpendedoraTickets extends javax.swing.JFrame {

    //Declaramos los contadores
    int contadorR = 1;
    int contadorQ = 1;
    int contadorA = 1;
    int contadorC = 1;
    
    //Declaramos el Stack regalo
    Stack regalo = new Stack();
    
    //Declaramos el Queue queja
    Queue<Integer> queja = new LinkedList<>();
    
    //Declaramos el Queue abono 
    Queue<Integer> abono = new LinkedList<>();
    
    //Declaramos el Queue credito
    Queue<Integer> credito = new LinkedList<>();
    
    //Instancia de la clase BuscadorRecursivo
    BuscadorRecursivo Hyper = new BuscadorRecursivo();
    
    //Declaramos DefaultListModel
    DefaultListModel modelo = new DefaultListModel();
    
    /*Declaramos un ArrayList porque en el método recursivo
    necesitamos obtener un valor en específico; y dado que el Queue no cuenta con el método ".get" utilizamos un ArrayList en su lugar.*/
    ArrayList contenedor = new ArrayList<Integer>();
    
    //Instancia de la clase Reiniciador
    Reiniciador principio = new Reiniciador();

    public ExpendedoraTickets() {
        initComponents();
        listExpendidos.setModel(modelo);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnAtenRegalo = new javax.swing.JButton();
        btnAtenCredito = new javax.swing.JButton();
        btnAtenQueja = new javax.swing.JButton();
        btnAtenAbono = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnExpenRegalo = new javax.swing.JButton();
        btnExpenQueja = new javax.swing.JButton();
        btnExpenCredito = new javax.swing.JButton();
        btnExpenAbono = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cbBuscador = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        txtTicket = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblRegalo = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblAbono = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblQueja = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lblCredito = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cbReiniciador = new javax.swing.JComboBox<>();
        btnReiniciar = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listExpendidos = new javax.swing.JList<>();
        btnMostrar = new javax.swing.JButton();
        cbMostrador = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(245, 208, 34));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Máquina expendedora de");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tickets");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(245, 208, 34));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        jPanel4.setPreferredSize(new java.awt.Dimension(267, 123));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Atención");

        btnAtenRegalo.setText("Atender regalo");
        btnAtenRegalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenRegaloActionPerformed(evt);
            }
        });

        btnAtenCredito.setText("Atender crédito");
        btnAtenCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenCreditoActionPerformed(evt);
            }
        });

        btnAtenQueja.setText("Atender queja");
        btnAtenQueja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenQuejaActionPerformed(evt);
            }
        });

        btnAtenAbono.setText("Atender abono");
        btnAtenAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenAbonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAtenRegalo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAtenAbono, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAtenQueja, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtenCredito)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtenRegalo)
                    .addComponent(btnAtenQueja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtenCredito)
                    .addComponent(btnAtenAbono))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(245, 208, 34));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        jPanel5.setPreferredSize(new java.awt.Dimension(267, 123));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Expendedora");

        btnExpenRegalo.setText("Tícket de regalo");
        btnExpenRegalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpenRegaloActionPerformed(evt);
            }
        });

        btnExpenQueja.setText("Tícket de queja");
        btnExpenQueja.setMaximumSize(new java.awt.Dimension(111, 23));
        btnExpenQueja.setMinimumSize(new java.awt.Dimension(111, 23));
        btnExpenQueja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpenQuejaActionPerformed(evt);
            }
        });

        btnExpenCredito.setText("Tícket de crédito");
        btnExpenCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpenCreditoActionPerformed(evt);
            }
        });

        btnExpenAbono.setText("Tícket de abono");
        btnExpenAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpenAbonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExpenAbono)
                            .addComponent(btnExpenRegalo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExpenQueja, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnExpenCredito)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExpenRegalo)
                    .addComponent(btnExpenQueja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExpenAbono)
                    .addComponent(btnExpenCredito))
                .addGap(11, 11, 11))
        );

        jPanel6.setBackground(new java.awt.Color(245, 208, 34));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Buscador");

        cbBuscador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbBuscador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el tipo de tícket", "Regalo", "Queja", "Abono", "Crédito" }));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Seleccione el número de tícket.");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbBuscador, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(btnBuscar)
                            .addGap(167, 167, 167))
                        .addComponent(txtTicket, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(33, 33, 33))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addGap(20, 20, 20))
        );

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 208, 34), 2));
        jPanel7.setPreferredSize(new java.awt.Dimension(379, 452));

        jPanel8.setBackground(new java.awt.Color(245, 208, 34));
        jPanel8.setPreferredSize(new java.awt.Dimension(355, 73));

        lblRegalo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblRegalo.setText("Regalo");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(lblRegalo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegalo)
                .addGap(28, 28, 28))
        );

        jPanel9.setBackground(new java.awt.Color(245, 208, 34));
        jPanel9.setPreferredSize(new java.awt.Dimension(355, 73));

        lblAbono.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblAbono.setText("Abono");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(lblAbono)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAbono)
                .addGap(28, 28, 28))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Regalo siguiente:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Queja siguiente:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Abono a tarjeta siguiente:");

        jPanel10.setBackground(new java.awt.Color(245, 208, 34));
        jPanel10.setPreferredSize(new java.awt.Dimension(355, 73));

        lblQueja.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblQueja.setText("Queja");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(lblQueja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblQueja)
                .addGap(28, 28, 28))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Crédito siguiente:");

        jPanel11.setBackground(new java.awt.Color(245, 208, 34));
        jPanel11.setPreferredSize(new java.awt.Dimension(355, 73));

        lblCredito.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCredito.setText("Crédito");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(lblCredito)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCredito)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(135, 135, 135))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel3))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel5))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel6)))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Panel de control");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Visor de control");

        jPanel12.setBackground(new java.awt.Color(245, 208, 34));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        jPanel12.setPreferredSize(new java.awt.Dimension(267, 123));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Reiniciador de conteo");

        cbReiniciador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbReiniciador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona qué conteo quieres reiniciar", "Regalo", "Queja", "Abono", "Crédito" }));

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReiniciar)
                    .addComponent(cbReiniciador, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbReiniciador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReiniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(245, 208, 34));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        jPanel14.setPreferredSize(new java.awt.Dimension(267, 123));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Mostrador de expendidos");

        jScrollPane2.setViewportView(listExpendidos);

        btnMostrar.setText("Mostrar / Actualizar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        cbMostrador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbMostrador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona qué conteo quieres mostrar", "Regalo", "Queja", "Abono", "Crédito" }));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel15))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMostrar)
                            .addComponent(cbMostrador, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMostrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnMostrar)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void btnExpenRegaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpenRegaloActionPerformed
        // TODO add your handling code here:        
        regalo.push(contadorR);
        JOptionPane.showMessageDialog(null,"Tícket R-" + regalo.peek() + " ha sido expendido.");
        contadorR = contadorR + 1;
    }//GEN-LAST:event_btnExpenRegaloActionPerformed
  
    private void btnAtenRegaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenRegaloActionPerformed
        // TODO add your handling code here:
        if(regalo.isEmpty() == true){
           JOptionPane.showMessageDialog(
                   null,"No hay tickets de regalo que atender.");
        }else if(regalo.size() == 1){
            JOptionPane.showMessageDialog(
                    null,"Tícket R-" + regalo.get(0) + " ha sido atendido.");
            regalo.pop();
            JOptionPane.showMessageDialog(
                    null,"Ya no quedan mas tickets de regalo por atender.");
            lblRegalo.setText("  -----");
        }else{
            JOptionPane.showMessageDialog(
                    null,"Tícket R-" + regalo.remove(0) + " ha sido atendido.");
            JOptionPane.showMessageDialog(
                    null,"El siguiente número en atenderse será el tícket R-" + regalo.get(0) + ".");
            lblRegalo.setText("   R-" + regalo.get(0));
        }       
    }//GEN-LAST:event_btnAtenRegaloActionPerformed

    private void btnExpenQuejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpenQuejaActionPerformed
        // TODO add your handling code here:
        queja.offer(contadorQ);
        JOptionPane.showMessageDialog(null,"Tícket Q-" + contadorQ + " ha sido expendido.");
        contadorQ = contadorQ + 1;
    }//GEN-LAST:event_btnExpenQuejaActionPerformed

    private void btnAtenQuejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenQuejaActionPerformed
        // TODO add your handling code here:
        if(queja.isEmpty() == true){
            JOptionPane.showMessageDialog(
                    null,"No hay tíckets de queja que atender.");
        }else if(queja.size() == 1){
            JOptionPane.showMessageDialog(
                    null,"Tícket Q-" + queja.poll() + " ha sido atendido.");
            JOptionPane.showMessageDialog(
                    null,"Ya no quedan mas tíckets de queja por atender.");
            lblQueja.setText(" -----");
        }else{
            JOptionPane.showMessageDialog(
                    null,"Tícket Q-" + queja.poll() + " ha sido atendido.");
             JOptionPane.showMessageDialog(
                    null,"El siguiente tícket en atenderse será el tícket Q-" + queja.element() + ".");
            lblQueja.setText("  Q-" + queja.element());
        }
    }//GEN-LAST:event_btnAtenQuejaActionPerformed

    private void btnExpenAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpenAbonoActionPerformed
        // TODO add your handling code here:
        abono.offer(contadorA);
        JOptionPane.showMessageDialog(null,"Tícket A-" + contadorA + " ha sido expendido.");
        contadorA = contadorA + 1;
    }//GEN-LAST:event_btnExpenAbonoActionPerformed

    private void btnAtenAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenAbonoActionPerformed
        // TODO add your handling code here:
        if(abono.isEmpty() == true){
            JOptionPane.showMessageDialog(
                    null,"No hay tickets de abono que atender.");
        }else if(abono.size() == 1){
            JOptionPane.showMessageDialog(
                    null,"Tícket A-" + abono.poll() + " ha sido atendido.");
            JOptionPane.showMessageDialog(
                    null,"Ya no quedan mas tickets de abono por atender.");
            lblAbono.setText("  -----");
        }else{
            JOptionPane.showMessageDialog(
                    null,"Tícket Q-" + abono.poll() + " ha sido atendido.");
            JOptionPane.showMessageDialog(
                    null,"El siguiente tícket en atenderse será el tícket A-" + abono.element() + ".");
            lblAbono.setText("   A-" + abono.element());
        }
    }//GEN-LAST:event_btnAtenAbonoActionPerformed

    private void btnExpenCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpenCreditoActionPerformed
        // TODO add your handling code here:
        credito.offer(contadorC);
        JOptionPane.showMessageDialog(null,"Tícket C-" + contadorC + " ha sido expendido.");
        contadorC = contadorC + 1;
    }//GEN-LAST:event_btnExpenCreditoActionPerformed

    private void btnAtenCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenCreditoActionPerformed
        // TODO add your handling code here:
        if(credito.isEmpty() == true){
            JOptionPane.showMessageDialog(
                    null,"No hay tickets de crédito que atender.");
        }else if(credito.size() == 1){
            JOptionPane.showMessageDialog(
                    null,"Tícket C-" + credito.poll() + " ha sido atendido.");
            JOptionPane.showMessageDialog(
                    null,"Ya no quedan mas tickets de crédito por atender.");
            lblCredito.setText("  -----");
        }else{
            JOptionPane.showMessageDialog(
                    null,"Tícket C-" + credito.poll() + " ha sido atendido.");
            JOptionPane.showMessageDialog(
                    null,"El siguiente tícket en atenderse será el tícket C-" + credito.element() + ".");
            lblCredito.setText("   C-" + credito.element());
        }
    }//GEN-LAST:event_btnAtenCreditoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        int tipo = cbBuscador.getSelectedIndex();
        int numero = Integer.parseInt(txtTicket.getText());
        
        switch(tipo){
            case 1:
                int indiceDelRegaloBuscado = Hyper.busquedaBinariaRecursiva(regalo, numero, 0, regalo.size() - 1);
                if(indiceDelRegaloBuscado == -1){
                    if(numero < contadorR){
                    JOptionPane.showMessageDialog(null, "El ticket R-" + numero + " ya fue atendido.");
                    }else{
                    JOptionPane.showMessageDialog(null, "El ticket R-" + numero + " no se expendido aún.");
                    }
                }else{
                JOptionPane.showMessageDialog(null, "El ticket R-" + numero + " si se encuentra, y está en la posición "+ (indiceDelRegaloBuscado+1));
                }
                break;
            case 2:
                int a = queja.size();
                    for(int i = 0; i < a; i++){
                        contenedor.add(queja.element());
                        queja.poll();
                    }
                int b = contenedor.size();
                    for(int i = 0; i < b; i++){
                        queja.offer((int) contenedor.get(i));
                    }
                int indiceDeLaQuejaBuscada = Hyper.busquedaBinariaRecursiva2(contenedor, numero, 0, queja.size() - 1);
                if(indiceDeLaQuejaBuscada == -1){
                    if(numero < contadorQ){
                    JOptionPane.showMessageDialog(null, "El ticket Q-" + numero + " ya fue atendido.");
                    }else{
                    JOptionPane.showMessageDialog(null, "El ticket Q-" + numero + " no se ha expendido aún.");
                    }
                    }else{
                    JOptionPane.showMessageDialog(null, "El ticket Q-" + numero + " si se encuentra, y está en la posición "+ (indiceDeLaQuejaBuscada+1));
                    }
                    contenedor.clear();    
                break;
            case 3:
                int c = abono.size();
                    for(int i = 0; i < c; i++){
                        contenedor.add(abono.element());
                        abono.poll();
                    }
                int d = contenedor.size();
                    for(int i = 0; i < d; i++){
                        abono.offer((int) contenedor.get(i));
                    }
                int indiceDelAbonoBuscado = Hyper.busquedaBinariaRecursiva2(contenedor, numero, 0, abono.size() - 1);
                if(indiceDelAbonoBuscado == -1){
                    if(numero < contadorA){
                    JOptionPane.showMessageDialog(null, "El ticket A-" + numero + " ya fue atendido.");
                    }else{
                    JOptionPane.showMessageDialog(null, "El ticket A-" + numero + " no se ha expendido aún.");
                    }
                    }else{
                    JOptionPane.showMessageDialog(null, "El ticket A-" + numero + " si se encuentra, y está en la posición "+ (indiceDelAbonoBuscado+1));
                    }
                    contenedor.clear(); 
                break;
            case 4:
                int e = credito.size();
                    for(int i = 0; i < e; i++){
                        contenedor.add(credito.element());
                        credito.poll();
                    }
                int f = contenedor.size();
                    for(int i = 0; i < f; i++){
                        credito.offer((int) contenedor.get(i));
                    }
                int indiceDelCreditoBuscado = Hyper.busquedaBinariaRecursiva2(contenedor, numero, 0, credito.size() - 1);
                if(indiceDelCreditoBuscado == -1){
                    if(numero < contadorC){
                    JOptionPane.showMessageDialog(null, "El ticket C-" + numero + " ya fue atendido.");
                    }else{
                    JOptionPane.showMessageDialog(null, "El ticket C-" + numero + " no se ha expendido aún.");
                    }
                    }else{
                    JOptionPane.showMessageDialog(null, "El ticket C-" + numero + " si se encuentra, y está en la posición "+ (indiceDelCreditoBuscado+1));
                    }
                    contenedor.clear();                
                break;
                }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
        int tipo = cbReiniciador.getSelectedIndex();
        
            switch(tipo){
                case 1:
                    principio.Reiniciador(regalo);
                    contadorR = 1;
                    break;
                case 2:
                    principio.Reiniciador2(queja);
                    contadorQ = 1;
                    break;
                case 3:
                    principio.Reiniciador2(abono);
                    contadorA = 1;
                    break;
                case 4:
                    principio.Reiniciador2(credito);
                    contadorC = 1;
                    break;
                }
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        int tipo = cbMostrador.getSelectedIndex();
        
            switch(tipo){
                case 1:
                    modelo.clear();
                    for (int i = 0; i < regalo.size(); i++) {
                        modelo.addElement("R-" + regalo.get(i));
                        }
                    break;
                case 2:
                    int a = queja.size();
                        for(int i = 0; i < a; i++){
                            contenedor.add(queja.element());
                            queja.poll();
                    }
                    int b = contenedor.size();
                        for(int i = 0; i < b; i++){
                            queja.offer((int) contenedor.get(i));
                    }
                    modelo.clear();
                    for(int i = 0; i < contenedor.size(); i++) {
                        modelo.addElement("Q-" + contenedor.get(i));
                    }
                    contenedor.clear();
                    break;
                case 3:
                    int c = abono.size();
                        for(int i = 0; i < c; i++){
                            contenedor.add(abono.element());
                            abono.poll();
                    }
                    int d = contenedor.size();
                        for(int i = 0; i < d; i++){
                            abono.offer((int) contenedor.get(i));
                    }
                    modelo.clear();
                    for(int i = 0; i < contenedor.size(); i++) {
                        modelo.addElement("A-" + contenedor.get(i));
                    }
                    contenedor.clear();
                    break;
                case 4:
                    int e = credito.size();
                        for(int i = 0; i < e; i++){
                            contenedor.add(credito.element());
                            credito.poll();
                    }
                    int f = contenedor.size();
                        for(int i = 0; i < f; i++){
                            credito.offer((int) contenedor.get(i));
                    }
                    modelo.clear();
                    for(int i = 0; i < contenedor.size(); i++) {
                        modelo.addElement("C-" + contenedor.get(i));
                    }
                    contenedor.clear();
                    break;
                }
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpendedoraTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpendedoraTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpendedoraTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpendedoraTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExpendedoraTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtenAbono;
    private javax.swing.JButton btnAtenCredito;
    private javax.swing.JButton btnAtenQueja;
    private javax.swing.JButton btnAtenRegalo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExpenAbono;
    private javax.swing.JButton btnExpenCredito;
    private javax.swing.JButton btnExpenQueja;
    private javax.swing.JButton btnExpenRegalo;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JComboBox<String> cbBuscador;
    private javax.swing.JComboBox<String> cbMostrador;
    private javax.swing.JComboBox<String> cbReiniciador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAbono;
    private javax.swing.JLabel lblCredito;
    private javax.swing.JLabel lblQueja;
    private javax.swing.JLabel lblRegalo;
    private javax.swing.JList<String> listExpendidos;
    private javax.swing.JTextField txtTicket;
    // End of variables declaration//GEN-END:variables
}
